#!/bin/bash
if [[ $EUID -ne 0 ]];
then
    exec pkexec --disable-internal-agent "$0" "$@"
fi
# JUST AN EXPERIMENTAL THING

while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    --drive)
    DRIVEDEVICE="$2"
    shift # past argument
    shift # past value
    ;;
    --username)
    HOLOUSER="$2"
    shift # past argument
    shift # past value
    ;;
    --password)
    HOLOPASS="$2"
    shift # past argument
    shift # past value
    ;;
    --root_password)
    ROOTPASS="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    echo "Unknown option: $1"
    exit 1
    ;;
esac
done

ROOTLOCATION=/tmp/holo_root
INSTALLLOCATION=${ROOTLOCATION}/rootfs
HOMELOCATION_TEMP=/tmp/holo_home
SNAPSHOT_FUTURELOC=${HOMELOCATION_TEMP}/.steamos/installcontainer
SUBVOL=$(ls /etc/holoinstall | grep holoiso | sed -s 's/.img.zst//g')
SUBVOLLOCATION=/tmp/subvol
	
	DEVICE="/dev/${DRIVEDEVICE}"
	
	INSTALLDEVICE="${DEVICE}"
	
	echo ${DEVICE} | grep -q -P "^/dev/(nvme|loop|mmcblk)"
	if [ $? -eq 0 ]; then
		INSTALLDEVICE="${DEVICE}p"
	fi


	
	echo -e "\nCreating partitions..."
	sfdisk --delete ${DEVICE}
	wipefs -a ${DEVICE}
	parted ${DEVICE} mklabel gpt
	parted ${DEVICE} mkpart primary fat32 2M 256M
	parted ${DEVICE} set 1 boot on
	parted ${DEVICE} set 1 esp on
	parted ${DEVICE} mkpart primary btrfs 256M 15G
    parted ${DEVICE} mkpart primary ext4 15G 16G
    parted ${DEVICE} mkpart primary ext4 16G 100%
	root_partition="${INSTALLDEVICE}2"
    var_partition="${INSTALLDEVICE}3"
    home_partition="${INSTALLDEVICE}4"
	mkfs -t vfat ${INSTALLDEVICE}1
	fatlabel ${INSTALLDEVICE}1 holo_efi
	mkfs -t btrfs -f ${root_partition}
	btrfs filesystem label ${root_partition} holo_root
    mkfs.ext4 -F ${var_partition}
    e2label ${var_partition} holo_var
    mkfs.ext4 -F ${home_partition}
    e2label ${home_partition} holo_home

    sync && udevadm trigger
    echo "Starting to bootstrap installation..."
    holoiso_bootstrap --username "${HOLOUSER}" --password "${HOLOPASS}" --root_password "${ROOTPASS}"
