#!/bin/sh

# Copyright 1999 Raphal Hertzog <hertzog@debian.org>
# See the README file for the license.

# This script does output additionnal mkisofs options
# depending on the ARCH and the CD number.

# Type can be "bin" or "src"
TYPE=$1
# The CD number
CD=$2

# No additional options by default
OPTS=

case "$ARCH" in
  i386) 
    OPTS="-J -joliet-long"
    ;;
  amd64) 
    OPTS="-J -joliet-long"
    ;;
  alpha)
    OPTS="-J -joliet-long"
    ;;
  arm*)
    OPTS="-J -joliet-long"
    ;;
  s390*)
    OPTS="-J -joliet-long"
    ;;
  *)
    #No options by default - don't know about other arches
    ;;
esac

echo -n "$OPTS "

